### ISSUE TITLE
Incorrect license - needs relicensing

### ISSUE THREAD

**Issue by PlNG** [mattdiamond/fuckitjs#12]
It needs the [WTFPL](http://en.wikipedia.org/wiki/WTFPL)!

**Comment by wtolson** [comment]
I second this motion.

**Comment by sethvargo** [comment]
+1

**Comment by ruicrsilva** [comment]
Ah fuck it! Just leave the actual one.

**Comment by subzey** [comment]
Did you notice that current license is also a valid FuckItJS script?

**Comment by mattdiamond** [comment]
https://twitter.com/#!/search/realtime/fuckitjs%20best%20license%20ever

The people have spoken, the license stays.
