### ISSUE TITLE
FuckIt doesn't work in production

### ISSUE THREAD

**Issue by daxhuiberts** [mattdiamond/fuckitjs#8]
Hi, I applied FuckIt in development and it indeed fixed some errors I was having for a long while now. But somehow in production it doesn't execute any code anymore. After some testing I figured out that it happens only when I minify my code. If i don't, it works correctly. Is there a way to fix that?

**Comment by mattdiamond** [comment]
Simple solution: don't minify your code. In fact, add additional line breaks just to be on the safe side.
